# -*- coding: utf-8 -*-
"""AmazonTextExtract

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nm4oUxVPzX2O989mnXyEwUmyM28kwmDw
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet  boto3 langchain-openai tiktoken python-dotenv langchain-community

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet  "amazon-textract-caller>=0.2.0"

!pip install amazon-textract-textractor

import boto3
from langchain.document_loaders import AmazonTextractPDFLoader

textract_client = boto3.client("textract", region_name="ap-south-1",aws_access_key_id='',aws_secret_access_key='')

file_path = "s3://aws-textract-bucket3/pdf_files/Nolan Covel Referral_DOC.pdf"
loader = AmazonTextractPDFLoader(file_path, client=textract_client)
documents = loader.load()

print(documents[0])

for document in documents:
  print(document)